### ISSUE TITLE
Add req_query and req_headers in error logger json_payload

### ISSUE THREAD

**Issue by brianmugweru** [kudobuzz/logger#22]
#### PreSubmission Checklist

- [x] The necessary labels have added
- [x] I have assigned issues to the right project

#### Issue Summary
Error details for req_query and req_header logger payload to help in easy debugging of issues on google_stack_driver

#### Related Issues
https://github.com/kudobuzz/socialreviews-apm/issues/339

**Comment by obengwilliam** [comment]
@brianmugweru  by the way i dont think we should logging the entire req
and req headers.  
Lets log what we need from them

**Comment by brianmugweru** [comment]
Closing this issue
